README.md
This PR adds 2 resources:
Android development blog https://vladsonkin.com/
Android development newsletter https://vladsonkin.com/android-newsletter/
=> Add vladsonkin.com to blogs and newsletters sections

README.md
Added Coding Troops blog to the blog list. 👋
=> Added Coding Troops blog to list

README.md
Bare minimum skillsets required to crack an android developer interview. These are the minimum required skillset, make sure you are good.
=> Higher level skills required to crack an Android Developer interview

README.md
Added Turkish websites/courses and a youtube channel about Android development.
=> Added Turkish websites/courses

README.md
These are the changes I've made:   
Added pl-coding.com to the video courses
Added Leland Richardson to youtube channels
Made a new Category for Twitch channels dedicated to Android Programming and added two new twitch channels to the list/
=> Added Twitch Channels category and more.

README.md
One link is not found giving error of 404 so removed,
added/updated link of medium with new publication.
=> Added New Links & Removed 404 not found links

README.md
- Added MindOrks course.
- Added Elliott Troop twitch channel.
- Added a few more youtube channels.
=> Added a few more resources.

README.md
Can't miss these gems from Mark Murphy ;)
=> Added books by CommonsWare

README.md
Add [Android Developer Roadmap](https://github.com/mobile-roadmap/android-developer-roadmap) under Docs/Other > Other.
=> Add Android developer Roadmap

README.md
**description:** Added the following course on Udemy as a resource in **Video course** category
**course name:** The Complete Android Oreo Developer Course - Build 23 Apps!
**link:** https://www.udemy.com/course/the-complete-android-oreo-developer-course/
**rating:** 4.5/5
=> Added a new resource in Video course category

README.md
Added Android O & Java - The Complete Android Development Bootcamp a beginner friendly course.
=> Added Android Dev Bootcamp

README.md
- Added spanish resources
- Added The Big Nerd Ranch Guide book
- Fix typo in JA brackets
=> Add spanish resources

README.md
I've added some links and information regarding "Android Security", take a look ¡¡¡ I hope to can help you with more in the future.
Thanks
=> Android Security Info by corleone77

README.md
#10 I added the ANDROID™ 4 APPLICATION DEVELOPMENT book as a new learning resource.
=> add "ANDROID™ 4 APPLICATION DEVELOPMENT" book.

README.md
#10 - Is a great way to get to know the most recommended practices for native android development, also having the possibility to get certified.
=> Adding certification as a study guide

README.md
Hello there!
I just added a very cool and nice course for building apps with kotlin.
It worth considering, Thanks!
=> Add Course for building Native app with Kotlin

README.md
The resources are not available anymore with the shut down of caster.io
https://articles.caster.io/business/caster-io-has-shut-down/
=> Remove Caster.io

README.md
I Added The Google Developer Scholarship and the Power of Community - Udacity
=> Update the README.md : Scholarship section.

README.md
Here's an android weekly newsletter focused on new development and updates of Android universe.
https://blog.canopas.com/tagged/canopas-android-weekly
=> Adding new resouce for android weekly newsletter

README.md
**Paulina talks Android** 
Advance Kotlin Topics with easy explanations
Resource Link: https://www.youtube.com/c/PaulinatalksAndroid
=> Add Paulina talks Android
